### ISSUE TITLE
相应速度

### ISSUE THREAD

**Issue by Originhhh** [yj-liuzepeng/chatgpt-zh#2]
大佬，在你的网站上，进行测试，比调用post api感觉更快，这是因为什么呢

**Comment by yj-liuzepeng** [comment]
怎么调用的post api，是用apipost工具调接口吗？

**Comment by Originhhh** [comment]
> 怎么调用的post api，是用apipost工具调接口吗？
用的python request

**Comment by yj-liuzepeng** [comment]
这个网站是部署在vercel上的，你request是不是开了🪜之后request的，和🪜也有关系吧，可以看一下 [vercel](https://blog.csdn.net/m0_70024326/article/details/129572529)

**Comment by Originhhh** [comment]
好的谢谢

**Comment by Originhhh** [comment]
> 这个网站是部署在vercel上的，你request是不是开了🪜之后request的，和🪜也有关系吧，可以看一下 [vercel](https://blog.csdn.net/m0_70024326/article/details/129572529)
您好， 如果我不想部署网站，直接请求，有什么快速稳定的方法推荐吗

**Comment by yj-liuzepeng** [comment]
这个服务是在国外，不搞🪜，访问不了
